### ISSUE TITLE
cover speaker

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/toolsDocs#21]
## cover pour HP
![image](https://user-images.githubusercontent.com/12049360/50767812-9070c680-127e-11e9-80ed-74e0ca63b37c.png)

objectif, faire quelque chose d'un peu plus fixe et clean. Une cover. Pour quoi ne pas tout sortir et fixer sur une planche? 
Déco? 

- [x] Panneau de décoration
- [x] demonter elec des HP
- [x] fixer l'elec dans la borne
- [x] fixer HP sur panneau deco
- [x] fixer panneau

**Comment by nicolasdb** [comment]
Same biz, scan HP et inkscape. 
![image](https://user-images.githubusercontent.com/12049360/50849783-4b30bf80-1378-11e9-8210-de5fd1a6f536.png)

**Comment by nicolasdb** [comment]
Ce serai en fait plus simple de tout changer que de chercher à sécuriser l'electrique des HP. 

Donc, j'ai ça en stock. 
TDA7492P Bluetooth 2x25 W Sans Fil V2.1 Bluetooth Audio Récepteur Conseil Module Amplificateur
![image](https://user-images.githubusercontent.com/12049360/50887071-7bb53f80-13f2-11e9-9849-34a5f58599c3.png)

> Alimentation: 2.1 interface d'alimentation DC 10 ~ 25V (avec protection de connexion inverse)
> Entrée audio: réception Bluetooth
> Impédance de sortie: 8 ohms maximum (peut piloter des enceintes d'impédance de 4, 6, 8 et 16 ohms)
> Puce d'amplificateur: TDA7492P (avec la lettre P est le double canal 25 watts) 25W + 25W
> Puissance de sortie: 2 * 25W 

+ transfo 12V
+ cable jack-jack 3.5 
ET c'est bouclé. 

Question: Réglage son se fait où?

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/50887303-24fc3580-13f3-11e9-9165-085e9df621d2.png)

**Comment by Jorgininho** [comment]
On va finallement garder l'elec de base des HP, l'ampli proposé est surdimensionné pour ces petits machins.
Je m'en vais finir de démonter les HP et l'elec associée.

**Comment by nicolasdb** [comment]
voilà le design qu'on va utiliser. 
Gros boulot de motif répétitif et adaptation au cas présent. 
![image](https://user-images.githubusercontent.com/12049360/50968078-54d23880-14da-11e9-9230-595138c83b40.png)

**Comment by nicolasdb** [comment]
On notera la petite surprise de style lorsqu'on applique le vernis à l'eau sur le hachurage laser dans le MDF. 
La texture créée est trop cool. ça fait un effet un peu écorce d'arbre et redonne du volume à la gravure.  Le touché est très intéressant aussi. 

![image](https://user-images.githubusercontent.com/12049360/51033924-4735b500-15a5-11e9-806d-58dfe93efc0a.png)

_note: j'applique 3 couches en insistant bien sur la gravure._
