### ISSUE TITLE
Games selection

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/toolsDocs#24]
- faire une belle sélection
- Réunir tout sur une seule carte SD, 12Go de ROM est bien assez. Pas besoin du HDD supplémentaire qui tire du power sur RPI.
- Backup iso sur le NAS.

**Comment by Jorgininho** [comment]
virtua fighter @Valonlisbeth

**Comment by Jorgininho** [comment]
windjammer
metalslug
mariokart
bomberman
puzzlebubble
1942
double dragon
zelda
advance war
street fighter 2
pac man
Turtles In Time
nba jam
pulstar

**Comment by Jorgininho** [comment]
toki
pang
sensible soccer

**Comment by Jorgininho** [comment]
To ply neogeo games, its needed to upload neogeo bios into the recal box
