### ISSUE TITLE
[CNC] Refurbishing of CNC : GOCNC hobby A4 basic

### ISSUE THREAD

**Issue by Jorgininho** [openfab-lab/toolsDocs#28]
Recently, a member of Openfab gave the lab a CNC he wasn't using anymore.
This is a tiny CNC which come in perfectly for the community to get hands on this kind of machines.

With this issue we'll try to write down the refurbishing of this machines, to make sure all person of the comminity that is interested can participate, to organize and make sure all info are accessible for future works on it.

So here are the objectives that have to be done for a simple usage :

- [x] Install Linux CNC on the machine dedicated to the CNC : 
This machine needs a computer dedicated to it, that will command it during whole time of the jobs.
The computer is unmounted, the trick here is know how the linuxCNC OS needs to be installed ? via USB or CD-ROM ?
![IMG_20190617_105455855](https://user-images.githubusercontent.com/10775713/59591860-1d9e2e00-90ef-11e9-88af-a0e8146a0a03.jpg)
From this step, the computer itself shall be able to command the CNC, first test needs to be done to check everything is alright (command on the 3 axis X,Y, Z)

- [x] Callibrate steps of the CNC machine
Small task, but mandatory is to callibrate the command of the engines via linuxCNC, this means make sure, for example, that a 1cm movement is a 1cm movement on the CNC

- [x] Flatening of the bed
Some of the 6 screws of the bed have their head little above the 0 level, just screw them so the level 0 of the bed is flat everywhere. Not tricky, just a make it works better task.

- [ ] Draw something, Understand setup of a jobs
The actual support on the CNC shall allow mounting of a pen, a good first job/test would be to draw something as it is.
This is also a good opportunity to understand how this machine is setup for a job, for example I don't see any homing end-stop, which is present on almost all 3-axis machines.

- [ ] connect the driller to the CNC
Actually, only the motors for the 3 axis are connected to the CNC, so to make it works completely it is needed to connect the driller. Some research needs to be done to know on which part of the command card we can connect the driller.
![commandConnect](https://user-images.githubusercontent.com/10775713/59592908-37407500-90f1-11e9-9d16-adbe44b5f84f.png)

- [x] Choose the supported driller 
There is actually no dedicated driller for the CNC, 2 solutions are proposed, a Dremel-like Proxxon, or a DC motor.
![IMG_20190617_103911732_HDR](https://user-images.githubusercontent.com/10775713/59593289-f39a3b00-90f1-11e9-986c-ca76896b506d.jpg)
For the solution choosen, a dedicated support needs to be designed, either replace the blue support plate already in place or design an adaptator to mount on it (2nd solution prefered because it shall support better the mechanical effort)
![IMG_20190617_103851819](https://user-images.githubusercontent.com/10775713/59593529-686d7500-90f2-11e9-8156-fbf2d3963fa8.jpg)

At this state, the CNC shall be usable for classical CNC jobs, what is needed shall be improvements
---------------------
WANTED IMPROVEMENTS

- [ ] Clamping system for the bed
Find a solution to fix material on the bed

- [ ] Replace computer by raspberry Pi
We are using an old computer because of the parallel connector, but it seems possible to use Raspberry Pi GPIO as parallel connector.

- [x] Y-belt tensor replacement
~~The beering used to tense the Y-belt seems of axis, should use a different screw with bigger diameter to make it more centered.~~ it's actually helping to have a bigger bearing, with smaller one, we feel a lot the steps from the belt. 
![IMG_20190617_103824986](https://user-images.githubusercontent.com/10775713/59594137-91dad080-90f3-11e9-9fcd-5b7449f3977a.jpg)

- [ ] Replacement of the command card
The actual configuration of this CNC is the same as the big CNC of Openfab, which make it a great introduction tool to CNC for Openfab members. But this command become an old technology and it should be a good improvement to replace the command card by a most recent one which allows USB connection (and end-stops!). This replacement need to occure then on both CNC to keep both machines accessible to Openfab members.

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/59603773-9199ff80-910a-11e9-9b9d-a67c4d6efeda.png)

https://www.youtube.com/watch?v=uDB2T3JMJFA

**Comment by O-Navid** [comment]
Here we are, Abdel and I are pretending to know what we are doing.
So here it is : we are currently downloading LinuxCNC and will soon install it on a USBfllashdrive callde Martens. Martens is a mainly white Flashdrive and will be our companion for the rest of the day.

We also had to download and install Win32-diskimager to write on that flashdrive (for apparently, just copy-pasting it won't work in this case).

3 minutes to go 'till the completion of the download.

**Comment by O-Navid** [comment]
Here we go, this is a very portable laptop. 
We plugged in a screen, an old keyboard and a old mouse.
Such a delight to see those oldies serve again *-*
#nostalgia #vintage #nicoyourenext

![64781746_857379804660847_2390657162926882816_n](https://user-images.githubusercontent.com/42928370/59607397-93b48c00-9113-11e9-98b1-695cd600cc21.jpg)

**Comment by nicolasdb** [comment]
ha et puis, ça peut être cool comme projet de faire une boite pour le PC controleur. 
https://buildyourcnc.com/AssembledElectronics.aspx

![image](https://user-images.githubusercontent.com/12049360/59609999-c6ad4e80-9118-11e9-8fce-6e3e8311e539.png)

**Comment by nicolasdb** [comment]
ha et puis, ça peut être cool comme projet de faire une boite pour le PC controleur. 
https://buildyourcnc.com/AssembledElectronics.aspx

![image](https://user-images.githubusercontent.com/12049360/59609999-c6ad4e80-9118-11e9-8fce-6e3e8311e539.png)

**Comment by abdel1130** [comment]
you have to enter boot with the usb linux graphic download

login: minicnc
passwords: minicnc

**Comment by abdel1130** [comment]
![image](https://user-images.githubusercontent.com/51918223/59612965-53a6d680-911e-11e9-8483-9ec33b7a22da.png)

**Comment by O-Navid** [comment]
TO DO : 

- install LIMIT switches for X, Y and Z axis
- Emergency STOP knob (find a practical spot on the machine to install it)
- define working area (on X, Y and Z)
- some cable management might be usefull too

After that we have a functionning machine, but with no tool.
Need to fix the spindle (we can use the Proxxon/Dremel : need to find a way to fix it on the machine)

Building a box for the Computer might be nice too.

Where are we going to place the machine ? We can fix it on a IKEA-rollroll-woody-wheely-drawer-table for instance.

**Comment by nicolasdb** [comment]
La config temporaire dans linuxCNC stepwizard, _il faudra ajuster pour identifier Estop et XYZ limits_
![stepconf pinsetup](https://user-images.githubusercontent.com/12049360/59753160-d5644480-9283-11e9-87a4-1450e1f24c9e.png)

Connexion de cette manière. 
![stepp2600 pinout](https://user-images.githubusercontent.com/12049360/59753161-d5644480-9283-11e9-8774-ee1d0ea4d964.jpg)

**Comment by nicolasdb** [comment]
Bon, puisque ça avance pas et que j'en ai quand même un peu besoin. 
En 2h30, 
j'ai ajouté une boite pour l'ordi, et j'ai ajouté les endstop X et Z. 
Merci à Francis pour avoir installé le Y. 
Reste à cabler et calibrer l'espace de travail. 

### boitier super hightech
![image](https://user-images.githubusercontent.com/12049360/60360360-d57ae780-99db-11e9-9162-a140cb6fcb0f.png)
![image](https://user-images.githubusercontent.com/12049360/60360365-dad83200-99db-11e9-9fef-0e19e1d451b3.png)

### switch limit X
![image](https://user-images.githubusercontent.com/12049360/60360395-ed526b80-99db-11e9-988f-868ed562917c.png)
### switch limit Z
![image](https://user-images.githubusercontent.com/12049360/60360445-065b1c80-99dc-11e9-9c6c-05180f1e5856.png)
### switch limit Y
![image](https://user-images.githubusercontent.com/12049360/60360503-27bc0880-99dc-11e9-971c-f5498097b158.png)

**Comment by O-Navid** [comment]
Limit Switch X, Y and Z are now wired to the micro-controller !
We tried connecting the 3 of them to the board, but it was to thick, so we managed another way out of it : switch X and Z are wired to switch Y, who in turn is connected to the board.
Voilà.

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/61035145-e7d72700-a3c6-11e9-8b7e-ef2d684ef4c5.png)

**Comment by nicolasdb** [comment]
Pour les adicts d'adobe. 
y a peut-être ici une solution pour le controle CNC 2D. 
https://diegomonzon.com/illustrator-to-g-code-panel-v2

**Comment by nicolasdb** [comment]
## installation fraiche de linuxcnc sur mint19
Pourquoi? parce que le debian d'origine, c'est un peu de la dèche de noyaux. et Inkscape est bloqué à sa version 0.48
https://forum.linuxcnc.org/9-installing-linuxcnc/35627-linuxcnc-on-linux-mint-19

**Comment by nicolasdb** [comment]
Note: Leadscrew pitch 3mm. 

## J'ai trouvé un bug
L'axe Z a un backlash de ouf. La vis est ok mais c'est le pasdevis (nut) qui doit avoir prit dans la gueule. Les autres axes sont bon.

**Comment by nicolasdb** [comment]
Curieux, c'est pas tant un bug, ya du jeu lorsqu'on monte pour faire le homing Z. J'avais réglé à 60mm le Zmax, j'ai rajouté des planchettes (2x3mm mdf) pour éloigner le contact et réglé à 55mm Zmax. 
ça marche, plus de jeu. 

Maintenant, surfacing. Pour mettre à zero la plaque de bois, (martyr), y a un script pour générer le gcode. 
https://github.com/LinuxCNC/simple-gcode-generators/tree/master/face

**Comment by nicolasdb** [comment]
FAQ: 
homing déconne? il faut bien que la machine ne soit pas en contact avec un limitswitch avant de lancer le homing. 
J'ai eu le coup, et Z cherchait vers le bas.

**Comment by nicolasdb** [comment]
https://ncviewer.com/

**Comment by nicolasdb** [comment]
Shiiiiiiiiiiiit. 
Surfaçage foiré. 
La mèche glisse et descend très progressivement. 

La broche proxxon ne doit pas être assez forte, j'ai pourtant serrer à la pince. 
Je reessayerai avec une mèche droite, ici elle était hélicoidale, mais quand même, j'ai jamais eu ça sur le Kress sur l'autre machine. 

pistes:
https://gocnc.de/shop/de/451/hf-milling-spindle-micro-hornet?c=39
http://www.aliexpress.com/item/4000293295742.html

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/197504538-74b6d342-c58c-40f1-b668-b042131cb5be.png)
 on a acheté une autre. 

Elle est plus rigide, même si pas encore foufou pour faire des choses de précision dans le 10ème de mm. 

Le système de controle choisi est la black BOX d'openbuilds. 
![image](https://user-images.githubusercontent.com/12049360/197504925-7a225e5e-14d1-480c-9776-e60f0dbc4b65.png)
https://openbuilds.com/builds/blackbox-motion-control-system.8320/

On passe en GRBL1.1. 

Le même controleur a été installé aussi sur le lasersaur pour uniformiser les controles machines. 
Opensource, merci.
