### ISSUE TITLE
how to move files from repo to repo?

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/toolsDocs#5]
@satblip 
Question technique. 
Quelle est la meilleure façon de déplacer un document d'un repo à un autre parce qu'il est mal rangé? 
Je peux faire un couper/coller en local et faire un commit. Mais ça casse l'historique non? 

Exemple concret:
Paul (ginsburg) a travaillé sur ceci
https://github.com/openfab-lab/openfab/blob/master/_space/machines/laser/preparation-fichier.md

J'aimerai que ce fichier arrive dans /toolsDocs au lieu de /openfab. Comment fait-on?

merci bisous.

**Comment by satblip** [comment]
@nicolasdb Tu peux, mais tu dois faire ça en ligne de commande :

https://gbayer.com/development/moving-files-from-one-git-repository-to-another-preserving-history/

C'est assez indigeste :D Mais si tu veux je peux le faire ?

De rien bises 😄

**Comment by nicolasdb** [comment]
ça n'a pas l'air si pire. 
c'est quelques lignes de codes à copier/coller. 

Je pense que ça risque d'arriver encore bien. Au fur et à mesure qu'on maitrisera mieux notre architecture de fichier. 
ça peut faire partie du cours "résolution de conflit". 

y a pas une soluce facile dans gitkraken ? :)

Sinon, dans des cas mineurs, mentionner la destination lors du commit du "delete"
et mentionner la source dans le commit "create" 
ça suffirait pour suivre l'historique manuellement.....
