### ISSUE TITLE
html&CSS - catégorie?

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/toolsDocs#6]
html et css, c'est de l'informatique ou de l'électronique? 
@zuperninja a trouvé ceci qui est pas mal. 
http://maitrisezhtmlcss.com/

ça reprend dans un ordre clair les tutos d'un peu partout sur le net.

**Comment by zuperninja** [comment]
C'est de l'informatique -> internet -> langage de programmation

**Comment by nicolasdb** [comment]
oui mais Electronique > logique de prog > language de prog.

**Comment by nicolasdb** [comment]
Donc on range ça où ?^^

**Comment by nicolasdb** [comment]
ok, c'est tranché chérie. 
J'ai mis dans informatique, pour le mostly software. Html, les OS, le réseaux. 
Et electronique, le code de prog lié à du hardware électronique, arduino and shit. 
https://github.com/openfab-lab/toolsDocs/blob/master/Informatics/learning2code.md

Par contre, @zuperninja , le lien que tu partageais est mort.
